"use client";
import { FormEvent, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
type Category = { id: string; name: string; emoji: string };
export default function CategoriesAdmin() {
  const [items, setItems] = useState<Category[]>([]), [name, setName] = useState(""), [emoji, setEmoji] = useState("🎁"), [message, setMessage] = useState("Loading…");
  async function load(){ if(!supabase)return; const {data,error}=await supabase.from("gift_categories").select("id,name,emoji").order("created_at"); setItems((data as Category[])||[]); if(error)setMessage(error.message); else setMessage(""); }
  useEffect(()=>{if(!supabase){setMessage("Supabase is not configured.");return;} supabase.auth.getSession().then(({data})=>{if(!data.session)setMessage("Please sign in at /admin first.");else load();});},[]);
  async function add(e:FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from("gift_categories").insert({name:name.trim(),emoji});setMessage(error?.message||"Category added.");if(!error){setName("");load();}}
  async function remove(id:string){if(!supabase||!confirm("Delete this category?"))return;const {error}=await supabase.from("gift_categories").delete().eq("id",id);setMessage(error?.message||"Category deleted.");if(!error)load();}
  return <main className="min-h-screen bg-[#080808] px-6 py-10 text-white lg:px-10"><div className="mx-auto max-w-4xl"><a href="/admin" className="text-sm text-[#d8b56a]">← Back to Admin</a><h1 className="mt-5 text-4xl font-semibold">Gift Categories</h1><p className="mt-3 text-white/45">Manage categories customers see in customised gifts.</p>{message&&<p className="mt-6 rounded-xl border border-[#d8b56a]/30 bg-[#d8b56a]/10 p-3 text-sm text-[#f1d99e]">{message}</p>}<form onSubmit={add} className="mt-8 flex flex-wrap gap-3 rounded-2xl border border-white/10 bg-[#0d0d0d] p-5"><input required value={emoji} onChange={e=>setEmoji(e.target.value)} className="w-16 rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-center" aria-label="Category emoji"/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Category name" className="min-w-64 flex-1 rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none focus:border-[#d8b56a]"/><button className="rounded-full bg-[#d8b56a] px-6 py-3 font-semibold text-black">Add category</button></form><div className="mt-6 space-y-3">{items.map(item=><div key={item.id} className="flex items-center justify-between rounded-2xl border border-white/10 bg-[#0d0d0d] p-5"><span className="text-lg">{item.emoji} <span className="ml-2">{item.name}</span></span><button onClick={()=>remove(item.id)} className="rounded-full border border-red-300/20 px-3 py-2 text-xs text-red-200">Delete</button></div>)}</div></div></main>;
}
