"use client";
import { FormEvent, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Product = { id: string; name: string; category: string; price: number; image_url: string | null };
const empty = { name: "", category: "", price: "", image_url: "", description: "", relationships: "", occasions: "" };

export default function AdminPage() {
  const [loggedIn, setLoggedIn] = useState<boolean | null>(null), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [message, setMessage] = useState(""), [products, setProducts] = useState<Product[]>([]), [form, setForm] = useState(empty), [editingId, setEditingId] = useState<string | null>(null);
  async function load() { if (!supabase) return; const { data } = await supabase.from("products").select("id,name,category,price,image_url").order("created_at", { ascending: false }); setProducts((data as Product[]) || []); }
  useEffect(() => { if (!supabase) { setLoggedIn(false); return; } supabase.auth.getSession().then(({ data }) => { setLoggedIn(Boolean(data.session)); if (data.session) load(); }); const { data: sub } = supabase.auth.onAuthStateChange((_event, session) => { setLoggedIn(Boolean(session)); if (session) load(); }); return () => sub.subscription.unsubscribe(); }, []);
  async function login(e: FormEvent) { e.preventDefault(); if (!supabase) return setMessage("Supabase environment variables are missing."); const { error } = await supabase.auth.signInWithPassword({ email, password }); setMessage(error?.message || "Signed in."); }
  async function add(e: FormEvent) { e.preventDefault(); if (!supabase) return; const slug = form.name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); const productFields = { name: form.name, category: form.category, price: Number(form.price), image_url: form.image_url || null, description: form.description }; const result = editingId ? await supabase.from("products").update(productFields).eq("id", editingId).select("id").single() : await supabase.from("products").insert({ ...productFields, slug }).select("id").single(); const error = result.error; if (!error && !editingId && result.data) { const names = form.relationships.split(",").map(v => v.trim()).filter(Boolean); const occasions = form.occasions.split(",").map(v => v.trim()).filter(Boolean); for (const name of names) { const { data } = await supabase.from("relationships").select("id").eq("name", name).maybeSingle(); if (data) await supabase.from("product_relationships").insert({ product_id: result.data.id, relationship_id: data.id }); } for (const name of occasions) { const { data } = await supabase.from("occasions").select("id").eq("name", name).maybeSingle(); if (data) await supabase.from("product_occasions").insert({ product_id: result.data.id, occasion_id: data.id }); } } setMessage(error?.message || (editingId ? "Product updated successfully." : "Product added successfully.")); if (!error) { setForm(empty); setEditingId(null); load(); } }
  function edit(product: Product) { setEditingId(product.id); setForm({ ...empty, name: product.name, category: product.category, price: String(product.price), image_url: product.image_url || "" }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function remove(id: string) { if (!supabase || !confirm("Delete this product?")) return; const { error } = await supabase.from("products").delete().eq("id", id); setMessage(error?.message || "Product deleted."); if (!error) load(); }
  if (loggedIn === null) return <main className="min-h-screen bg-[#080808] p-10 text-white">Loading…</main>;
  if (!loggedIn) return <main className="flex min-h-screen items-center justify-center bg-[#080808] px-6 text-white"><form onSubmit={login} className="w-full max-w-md rounded-3xl border border-white/10 bg-[#0d0d0d] p-8"><p className="text-xs uppercase tracking-[0.35em] text-[#d8b56a]">Ganpati Studio</p><h1 className="mt-3 text-3xl font-semibold">Admin login</h1><input required type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} className="mt-7 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none" /><input required type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} className="mt-4 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none" /><button className="mt-6 w-full rounded-full bg-[#d8b56a] py-3.5 font-semibold text-black">Sign in</button>{message && <p className="mt-4 text-xs text-red-200">{message}</p>}</form></main>;
  return <main className="min-h-screen bg-[#080808] px-6 py-10 text-white lg:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.35em] text-[#d8b56a]">Ganpati Studio</p><h1 className="mt-2 text-4xl font-semibold">Product Admin</h1></div><button onClick={() => supabase?.auth.signOut()} className="rounded-full border border-white/15 px-5 py-2 text-sm">Sign out</button></div>{message && <p className="mt-6 rounded-xl border border-[#d8b56a]/30 bg-[#d8b56a]/10 p-3 text-sm text-[#f1d99e]">{message}</p>}<div className="mt-10 grid gap-8 lg:grid-cols-[360px_1fr]"><form onSubmit={add} className="h-fit rounded-3xl border border-white/10 bg-[#0d0d0d] p-6"><h2 className="text-xl">{editingId ? "Edit product" : "Add product"}</h2>{([["name","Product name",true],["category","Category",true],["price","Starting price",true],["image_url","Image URL",false],["description","Description",false],["relationships","Relationships (Mom, Dad, Couple)",false],["occasions","Occasions (Birthday, Wedding)",false]] as const).map(([key, placeholder, required]) => <input key={key} required={required} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} placeholder={placeholder} type={key === "price" ? "number" : "text"} className="mt-4 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm outline-none focus:border-[#d8b56a]" />)}<button className="mt-5 w-full rounded-full bg-[#d8b56a] py-3.5 text-sm font-semibold text-black">{editingId ? "Save changes" : "Add product"}</button>{editingId && <button type="button" onClick={() => { setEditingId(null); setForm(empty); }} className="mt-3 w-full text-sm text-white/50">Cancel edit</button>}</form><section><h2 className="text-xl">Products ({products.length})</h2><div className="mt-4 space-y-3">{products.map(p => <div key={p.id} className="flex items-center justify-between rounded-2xl border border-white/10 bg-[#0d0d0d] p-4"><div><p className="text-xs text-[#d8b56a]">{p.category}</p><p className="mt-1">{p.name}</p><p className="mt-1 text-xs text-white/45">₹{p.price}</p></div><div className="flex gap-2"><button onClick={() => edit(p)} className="rounded-full border border-[#d8b56a]/30 px-3 py-2 text-xs text-[#d8b56a]">Edit</button><button onClick={() => remove(p.id)} className="rounded-full border border-red-300/20 px-3 py-2 text-xs text-red-200">Delete</button></div></div>)}</div></section></div></div></main>;
}
